[package]
name = "rust-http-server"
version = "0.1.0"
authors = ["Matthew Allen <matthew.allen@matthewsbrain.com>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
bytes = "1.3.0"                                  # helps manage buffers
flate2 = "1.0.34"
